create database Retail_analysis

SELECT TOP 2 * FROM customer
select TOP 2 * from prod_cat_info
select top 2 * from transactions

--data prep and understanding : 

--1. total no. of rows in each table? 
select count(*) as cnt_cust from customer
select count(*) as cnt_prod from prod_cat_info
select count(*) as cnt_trans from transactions

--2. What is the total number of transactions that have returned?
select count(distinct(transaction_id)) as total_trans from transactions
where Qty < 0 

--3. convert dates into valid date formats before proceeding :
select convert(date,tran_date , 105) from transactions

--4. What is the time range for transaction data available for analysis? Show the output in 
--   number of days , months and years simultaneously in different columns. 
select
DATEDIFF(YEAR,MIN(convert(date,tran_date , 105)),MAX(convert(date,tran_date , 105))) AS DIFF_YEARS,
DATEDIFF(MONTH,MIN(convert(date,tran_date , 105)),MAX(convert(date,tran_date , 105))) AS DIFF_MONTHS,
DATEDIFF(DAY,MIN(convert(date,tran_date , 105)),MAX(convert(date,tran_date , 105))) AS DIFF_DAYS
FROM transactions

--5. WHICH PRODUCT CATEGORY DID THE SUBCATEGORY 'DIY' BELONGS TO?
SELECT prod_cat,prod_subcat FROM prod_cat_info
WHERE prod_subcat = 'DIY' 



-- DATA ANALYSIS --
--1. Which channel is most frequently used for transactions?
select store_type,count(Store_type) as cnt from transactions 
 group by Store_type
 order by cnt desc 

--2. What is the count of male and female customers in the database? 
select Gender,count(gender) as CNT from Customer
WHERE gender is not null
GROUP BY Gender

--3. From which city do we have the maximum number of customers and how many? 
select top 1 city_code,count(city_code) as cnt from Customer
group by city_code 
order by cnt desc 

--4. How many subcategories are there under a books category? 
select prod_cat,prod_subcat from prod_cat_info
where prod_cat = 'books'

--5. What is the maximum quantity of product ever ordered?
select prod_cat_code,max(Qty) as max_qty from transactions 
group by prod_cat_code

--6. What is the net total revenue generated in categories electronics and books? 
select SUM(TOTAL_AMT) AS TOTAL_REVENUE FROM prod_cat_info AS A
LEFT JOIN TRANSACTIONS AS B 
ON A.prod_cat_code = B.prod_cat_code AND A.prod_sub_cat_code = B.prod_subcat_code
WHERE prod_cat = 'ELECTRONICS' OR prod_cat = 'BOOKS' 

--7. How many customers have > 10 transactions with us, excluding returns? 
select COUNT(*) AS TOTAL_CNT FROM(
               select cust_id,count(distinct(transaction_id)) as trans from Transactions
               group by cust_id
               having count(distinct(transaction_id)) > 10 
                ) AS A 

--8. What is the combined revenue earned from 'electronics', 'clothing' 
--   categories , from "flagship stores" ? 
select sum(cast(total_amt as float)) as total_cnt from prod_cat_info as a 
join Transactions as b 
on a.prod_cat_code = b.prod_cat_code and a.prod_sub_cat_code = b.prod_subcat_code
where prod_cat in ('clothing','electronics') and Store_type in ('Flagship store') and qty >0 

--9.What is the total revenue generated from male customer in electronics category?
--  output should display total revenue by prod_subcat?  
select prod_subcat,sum(cast(total_amt as float)) from Customer as a 
join Transactions as b 
on a.customer_Id = b.cust_id 
join prod_cat_info as c
on b.prod_cat_code = c.prod_cat_code and b.prod_subcat_code = c.prod_sub_cat_code
where a.gender = 'M' and c.prod_cat = 'electronics' 
group by prod_subcat

--10. What is the percentage of sales and returns by sub category; 
--    describe only top 5 categories in terms of sales?
select * from (
select top 5 prod_subcat,(sum(cast(total_amt as float))/(select sum(cast(total_amt as float)) 
as total_sales from Transactions where qty >  0 ))as percent_sales from prod_cat_info as a 
join Transactions as b 
on a.prod_cat_code = b.prod_cat_code 
and a.prod_sub_cat_code = b.prod_subcat_code
where Qty > 0 
group by prod_subcat
order by percent_sales desc 
) as t1 
join
(
select prod_subcat,(sum(cast(total_amt as float))/(select sum(cast(total_amt as float)) 
as total_sales from Transactions where qty <  0 ))as percent_sales from prod_cat_info as a 
join Transactions as b 
on a.prod_cat_code = b.prod_cat_code 
and a.prod_sub_cat_code = b.prod_subcat_code
where Qty < 0 
group by prod_subcat) as t2
on t1.prod_subcat = t2.prod_subcat

--11. For all the customers age between 25 to 35 years find what is the net total revenue 
--  generated by these customers in last 30 days of transaction from max transaction date 
--  available in data? 

--customer b/w age 25 and 35
SELECT * FROM (
select * from (
select cust_id, DATEDIFF(year,dob,max_date) as age, total_revenue from (
select cust_id,DOB,max(convert(date,tran_date,105)) as max_date, sum(cast(total_amt as float)) 
as total_revenue from Customer as a 
join Transactions as b 
on a.customer_Id = b.cust_id
where qty > 0
group by cust_id, DOB
) as t 
      ) as T
where age between 25 and 35 
) as A 
JOIN (
-- last 30 days transaction 
select cust_id , convert(date, tran_date,105) as trans_date from Transactions
group by cust_id ,convert(date, tran_date,105)
having convert(date, tran_date,105) >= (select dateadd(day, -30,max(convert(date, tran_date,105))) 
as cutoff_date  from Transactions)
) as B 
on A.cust_id= B.cust_id 

--12. Which product category has seen the max value of returns in last 3 months of transactions? 
select top 1 prod_cat_code, sum(returns) as total_returns from (
select prod_cat_code, convert(date, tran_date,105)as trans_date , sum(qty) as returns 
from Transactions
where qty < 0 
group by prod_cat_code ,convert(date, tran_date,105)
having convert(date, tran_date,105) >= (select dateadd(MONTH , -3,max(convert(date, tran_date,105))) 
as cutoff_date  from Transactions) 
)as A 
group by prod_cat_code
order by total_returns


--13. Which storetype sells the maximum products ; by value of sales amount and by quantity sold? 
select store_type, sum(cast(total_amt as float)) as revenue, sum(qty) as quatity from transactions
where qty > 0 
group by store_type 
order by revenue desc , quatity desc 

--14. What are the categories for which average revenue is above ovwrall average? 
select prod_cat_code , AVG(cast(total_amt as float)) as avg_revenue from Transactions 
where qty > 0 
group by prod_cat_code
having avg(cast(total_amt as float)) >= (select avg(cast(total_amt as float)) as avg_revenue 
from Transactions where qty > 0)

--15. Find the average and total revenueby each sub category for the categories which are among top 5
--    categories in terms of quantity sold? 
select prod_subcat_code, sum(cast(total_amt as float)) as revenue, avg(cast(total_amt as float)) as avg_revenue 
from Transactions
where qty >0 and prod_cat_code in (select top 5 prod_cat_code from Transactions
                                   where qty > 0 
                                   group by prod_cat_code
                                   order by sum(qty) desc ) 
GROUP BY prod_subcat_code



